---
title: "Principle component analysis vs support vector machine"
author: "Dong Liang"
date: '2018-12-02'
slug: priciple-component-analysis-vs-support-vector-machine
tags: Machine learning
categories: Machine learning
---


## Load proteomics data

```{r, engine='python'}
import pandas as pd
import numpy as np

scan = pd.read_csv('/Users/DL/Documents/Jupyter project/Somascan Protein Creatinine/somascan.csv')
print(scan.head())
```

## Exploratory data analysis


## Data processing 
Covert pandas dataframe to matrix.
We build an internal `Data2matrix` class for `Pipeline` to use. We will need implement \
fit and transform functions inside the Data2matrix class.

```{r, engine='python'}
from sklearn.preprocessing import Imputer, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import cross_val_score, cross_val_predict
imputer = Imputer(strategy = 'mean')

class Data2matrix(BaseEstimator, TransformerMixin):
 def __init__(self, attribute_names = None):
  self.attribute_names = attribute_names
 def fit(self, X, y = None):
  return self
 def transform(self):
  return X.values.

num_pipeline = Pipeline([
    ('Data2matrix', Data2matrix()),
    ('std_scalar', StandardScaler()) ])
    
print(num_pipeline.fit_transform(X))
```




